dist: trusty
sudo: false
language: node_js
node_js:
  - "8.9.3"
addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - git clone -b dev https://github.com/MSFREACH/msf-reach-schema && cd msf-reach-schema && bash build.sh && cd -

install:
  - npm install

after_success: npm run coverage
