dist: trusty
sudo: true
language: node_js
node_js:
  - "6.10.0"
addons:
  postgresql: "9.6"

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - git clone https://github.com/usergroupcoop/msf-reach-schema && cd msf-reach-schema && bash build.sh && cd -

install:
  - npm install

after_success: npm run coverage
