version: 0.2

phases:
  install:
    commands:
      - npm install --production
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.npm/**/*'
